print ("this is a backslash \\")
print("this is double backslash \\\\")
print("this is a  /\\/\\/\\/\\/\\ mountain ")
print("he is \t happy")
print("this is a backslash \\ \n this is a double backslash \\\\ \n this is a /\\/\\/\\/\\/\\ mountain \n he is \t happy ")
print ('they\'re happy' )
print ("\U0001F6A6")
print(r"this is a backslash \ ")
print('they\'re happy')
print("hi nice to meet you \U0001F497 \nthey\'re here to see you ")
print(r"this is a /\/\/\/\/\ mountain")
print(3+2)
print(round(8/3, 3))
print(8//3)
print("y es\b\b\bno") 
