first_name , second_name = input("please provide your full name(space seperated): ").split(" ")
print("your full name is ---> " +first_name + " "+ second_name)
first_name , second_name = input("please provide your full name(comma seperated): ").split(",")
print("your full name is ---> " +first_name + " "+ second_name)
name_type = type(first_name)
print("type of firstname is ", name_type)
print("type of second is ", type(second_name))